### PR TITLE
Update base.html.twig to correctly load style.css when project is installed under a subdirectory 

### PR DESCRIPTION
**Pull request by rvd0167**
Make style.css loadable even if the project is installed under a subdirectory.

### CODE REVIEW

**Comment by antedebaas** [comment]
If you have a solution that includes not breaking other parts of the project I’m open to it.
See my comment here https://github.com/antedebaas/Viesti-Reports/issues/137#issuecomment-2275065320

**Comment by rvd0167** [comment]
Hi

I did make a pull request with this solution.
I did not break anything when installed on its own domain. And it is just for style.css.
.htaccess is already prepared for subdomain use with the BASE variable.
It is stated as such in the .htaccess file

Ron

14 aug 2024 21:00:45 Ante de Baas ***@***.***>:

**Comment by antedebaas** [comment]
the problem comes when running this in a subdirectory in the first place. 
The subdirectory will add to the path thus breaking all the policy, autoconfig and bimi hosting. As those have fixed paths in their standards. 

the .htaccess is a symfony default one and will not work on other servers like NGINX and ISS thus you can not rely on that.

If you can find a solution for these problems I can consider this

**Comment by rvd0167** [comment]
For a solution am I "allowed" to edit .env.local or is that route a no-go?

14 aug 2024 23:10:54 Ante de Baas ***@***.***>:

**Comment by antedebaas** [comment]
I fail to see what .env.local has to do with this. 
im also not telling you what to do or not to do with your copy of the projects code

**Comment by rvd0167** [comment]
Just because I had an idea for a completely different approach. Will give it a shot.


14 aug 2024 23:27:37 Ante de Baas ***@***.***>:

**Pull request closed without merging**
